In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import requests

# Pandas package használata

# CSV letöltése url ről

In [2]:
url = 'http://leszped.tmit.bme.hu/dl/movie_metadata.csv'
r = requests.get(url, allow_redirects=True)
open('data.csv', 'wb').write(r.content)

1494688

In [3]:
df = pd.read_csv('movie_metadata.csv', sep=',')

In [4]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
4                   131.0          NaN                      Documentary   

          ...          num_user_for_reviews language  country  content_rating  \
0         ...                        3054.0  English      USA           PG-13   
1         ...                        1238.0  English      USA           PG-13   
2         ...                         994.0  English       UK           PG-13   
3         ...                        2701.0  English      USA           PG-13   
4         ...                           NaN      NaN      NaN             NaN   

        budget  title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0  237000000.0      2009.0                  936.0        7.9          1.78   
1  300000000.0      2007.0                 5000.0        7.1          2.35   
2  245000000.0      2015.0                  393.0        6.8          2.35   
3  250000000.0      2012.0                23000.0        8.5          2.35   
4          NaN         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

# Igy állítod be h az összes oszlopot kiírja

In [5]:
pd.set_option('max_columns', None)

In [6]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
4                   131.0          NaN                      Documentary   

      actor_1_name                                        movie_title  \
0      CCH Pounder                                            Avatar    
1      Johnny Depp          Pirates of the Caribbean: At World's End    
2  Christoph Waltz                                           Spectre    
3        Tom Hardy                             The Dark Knight Rises    
4      Doug Walker  Star Wars: Episode VII - The Force Awakens    ...   

   num_voted_users  cast_total_facebook_likes          actor_3_name  \
0           886204                       4834             Wes Studi   
1           471220                      48350        Jack Davenport   
2           275868                      11700      Stephanie Sigman   
3          1144337                     106759  Joseph Gordon-Levitt   
4                8                        143                   NaN   

   facenumber_in_poster                                      plot_keywords  \
0                   0.0             avatar|future|marine|native|paraplegic   
1                   0.0  goddess|marriage ceremony|marriage proposal|pi...   
2                   1.0                bomb|espionage|sequel|spy|terrorist   
3                   0.0  deception|imprisonment|lawlessness|police offi...   
4                   0.0                                                NaN   

                                     movie_imdb_link  num_user_for_reviews  \
0  http://www.imdb.com/title/tt0499549/?ref_=fn_t...                3054.0   
1  http://www.imdb.com/title/tt0449088/?ref_=fn_t...                1238.0   
2  http://www.imdb.com/title/tt2379713/?ref_=fn_t...                 994.0   
3  http://www.imdb.com/title/tt1345836/?ref_=fn_t...                2701.0   
4  http://www.imdb.com/title/tt5289954/?ref_=fn_t...                   NaN   

  language country content_rating       budget  title_year  \
0  English     USA          PG-13  237000000.0      2009.0   
1  English     USA          PG-13  300000000.0      2007.0   
2  English      UK          PG-13  245000000.0      2015.0   
3  English     USA          PG-13  250000000.0      2012.0   
4      NaN     NaN            NaN          NaN         NaN   

   actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                   936.0         7.9          1.78                 33000  
1                  5000.0         7.1          2.35                     0  
2                   393.0         6.8          2.35                 85000  
3                 23000.0         8.5          2.35                164000  
4                    12.0         7.1           NaN                     0

In [7]:
df.tail()

color     director_name  num_critic_for_reviews  duration  \
5038  Color       Scott Smith                     1.0      87.0   
5039  Color               NaN                    43.0      43.0   
5040  Color  Benjamin Roberds                    13.0      76.0   
5041  Color       Daniel Hsia                    14.0     100.0   
5042  Color          Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
5038                      2.0                   318.0     Daphne Zuniga   
5039                      NaN                   319.0     Valorie Curry   
5040                      0.0                     0.0     Maxwell Moody   
5041                      0.0                   489.0     Daniel Henney   
5042                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes    gross                        genres  \
5038                   637.0      NaN                  Comedy|Drama   
5039                   841.0      NaN  Crime|Drama|Mystery|Thriller   
5040                     0.0      NaN         Drama|Horror|Thriller   
5041                   946.0  10443.0          Comedy|Drama|Romance   
5042                    86.0  85222.0                   Documentary   

     actor_1_name                 movie_title  num_voted_users  \
5038  Eric Mabius    Signed Sealed Delivered               629   
5039  Natalie Zea  The Following                         73839   
5040  Eva Boehnke       A Plague So Pleasant                38   
5041    Alan Ruck           Shanghai Calling              1255   
5042  John August          My Date with Drew              4285   

      cast_total_facebook_likes    actor_3_name  facenumber_in_poster  \
5038                       2283    Crystal Lowe                   2.0   
5039                       1753   Sam Underwood                   1.0   
5040                          0  David Chandler                   0.0   
5041                       2386     Eliza Coupe                   5.0   
5042                        163        Jon Gunn                   0.0   

                                          plot_keywords  \
5038             fraud|postal worker|prison|theft|trial   
5039       cult|fbi|hideout|prison escape|serial killer   
5040                                                NaN   
5041                                                NaN   
5042  actress name in title|crush|date|four word tit...   

                                        movie_imdb_link  num_user_for_reviews  \
5038  http://www.imdb.com/title/tt3000844/?ref_=fn_t...                   6.0   
5039  http://www.imdb.com/title/tt2071645/?ref_=fn_t...                 359.0   
5040  http://www.imdb.com/title/tt2107644/?ref_=fn_t...                   3.0   
5041  http://www.imdb.com/title/tt2070597/?ref_=fn_t...                   9.0   
5042  http://www.imdb.com/title/tt0378407/?ref_=fn_t...                  84.0   

     language country content_rating  budget  title_year  \
5038  English  Canada            NaN     NaN      2013.0   
5039  English     USA          TV-14     NaN         NaN   
5040  English     USA            NaN  1400.0      2013.0   
5041  English     USA          PG-13     NaN      2012.0   
5042  English     USA             PG  1100.0      2004.0   

      actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
5038                   470.0         7.7           NaN                    84  
5039                   593.0         7.5         16.00                 32000  
5040                     0.0         6.3           NaN                    16  
5041                   719.0         6.3          2.35                   660  
5042                    23.0         6.6          1.85                   456

In [8]:
len(df)

5043

# Logikai érték az egyes elmeknél, hogy nulla - e

In [9]:
df.isnull()

color  director_name  num_critic_for_reviews  duration  \
0     False          False                   False     False   
1     False          False                   False     False   
2     False          False                   False     False   
3     False          False                   False     False   
4      True          False                    True      True   
5     False          False                   False     False   
6     False          False                   False     False   
7     False          False                   False     False   
8     False          False                   False     False   
9     False          False                   False     False   
10    False          False                   False     False   
11    False          False                   False     False   
12    False          False                   False     False   
13    False          False                   False     False   
14    False          False                   False     False   
15    False          False                   False     False   
16    False          False                   False     False   
17    False          False                   False     False   
18    False          False                   False     False   
19    False          False                   False     False   
20    False          False                   False     False   
21    False          False                   False     False   
22    False          False                   False     False   
23    False          False                   False     False   
24    False          False                   False     False   
25    False          False                   False     False   
26    False          False                   False     False   
27    False          False                   False     False   
28    False          False                   False     False   
29    False          False                   False     False   
...     ...            ...                     ...       ...   
5013  False          False                   False     False   
5014  False          False                   False     False   
5015  False          False                   False     False   
5016  False          False                    True     False   
5017  False          False                   False     False   
5018  False          False                   False     False   
5019  False          False                   False     False   
5020   True          False                    True     False   
5021  False          False                   False     False   
5022  False          False                   False     False   
5023  False          False                   False     False   
5024  False          False                   False     False   
5025  False          False                   False     False   
5026  False          False                   False     False   
5027  False          False                   False     False   
5028  False          False                   False     False   
5029  False          False                   False     False   
5030  False          False                    True     False   
5031  False          False                   False     False   
5032  False          False                   False     False   
5033  False          False                   False     False   
5034  False          False                   False     False   
5035  False          False                   False     False   
5036  False          False                    True     False   
5037  False          False                   False     False   
5038  False          False                   False     False   
5039  False           True                   False     False   
5040  False          False                   False     False   
5041  False          False                   False     False   
5042  False          False                   False     False   

      director_facebook_likes  actor_

In [10]:
print("%d (sorok, amiben van NaN) / %d (összes)" % (len(df[df.isnull().any(axis=1)]), len(df)))

1287 (sorok, amiben van NaN) / 5043 (összes)


In [11]:
df['color']

0                  Color
1                  Color
2                  Color
3                  Color
4                    NaN
5                  Color
6                  Color
7                  Color
8                  Color
9                  Color
10                 Color
11                 Color
12                 Color
13                 Color
14                 Color
15                 Color
16                 Color
17                 Color
18                 Color
19                 Color
20                 Color
21                 Color
22                 Color
23                 Color
24                 Color
25                 Color
26                 Color
27                 Color
28                 Color
29                 Color
              ...       
5013               Color
5014               Color
5015     Black and White
5016               Color
5017               Color
5018               Color
5019               Color
5020                 NaN
5021               Color


# Pyformat.info --> print-es szintaxis miatt

# Törlése azoknak a soroknak amiben van NaN érték

In [12]:
df = df[~df.isnull().any(axis=1)]

In [13]:
len(df)

3756

In [14]:
df.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
5  Color     Andrew Stanton                   462.0     132.0   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
5                    475.0                   530.0   Samantha Morton   

   actor_1_facebook_likes        gross                           genres  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                 40000.0  309404152.0         Action|Adventure|Fantasy   
2                 11000.0  200074175.0        Action|Adventure|Thriller   
3                 27000.0  448130642.0                  Action|Thriller   
5                   640.0   73058679.0          Action|Adventure|Sci-Fi   

      actor_1_name                                movie_title  \
0      CCH Pounder                                    Avatar    
1      Johnny Depp  Pirates of the Caribbean: At World's End    
2  Christoph Waltz                                   Spectre    
3        Tom Hardy                     The Dark Knight Rises    
5     Daryl Sabara                               John Carter    

   num_voted_users  cast_total_facebook_likes          actor_3_name  \
0           886204                       4834             Wes Studi   
1           471220                      48350        Jack Davenport   
2           275868                      11700      Stephanie Sigman   
3          1144337                     106759  Joseph Gordon-Levitt   
5           212204                       1873          Polly Walker   

   facenumber_in_poster                                      plot_keywords  \
0                   0.0             avatar|future|marine|native|paraplegic   
1                   0.0  goddess|marriage ceremony|marriage proposal|pi...   
2                   1.0                bomb|espionage|sequel|spy|terrorist   
3                   0.0  deception|imprisonment|lawlessness|police offi...   
5                   1.0  alien|american civil war|male nipple|mars|prin...   

                                     movie_imdb_link  num_user_for_reviews  \
0  http://www.imdb.com/title/tt0499549/?ref_=fn_t...                3054.0   
1  http://www.imdb.com/title/tt0449088/?ref_=fn_t...                1238.0   
2  http://www.imdb.com/title/tt2379713/?ref_=fn_t...                 994.0   
3  http://www.imdb.com/title/tt1345836/?ref_=fn_t...                2701.0   
5  http://www.imdb.com/title/tt0401729/?ref_=fn_t...                 738.0   

  language country content_rating       budget  title_year  \
0  English     USA          PG-13  237000000.0      2009.0   
1  English     USA          PG-13  300000000.0      2007.0   
2  English      UK          PG-13  245000000.0      2015.0   
3  English     USA          PG-13  250000000.0      2012.0   
5  English     USA          PG-13  263700000.0      2012.0   

   actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                   936.0         7.9          1.78                 33000  
1                  5000.0         7.1          2.35                     0  
2                   393.0         6.8          2.35                 85000  
3                 23000.0         8.5          2.35                164000  
5                   632.0         6.6          2.35                 24000

# Milyen kategorikus változók lehetnek: color, director_name, actor_1_name, actor_2_name, actor_3_name, language, country, content_rating

In [15]:
categorical_features = ['color', 'director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name', 'language', 'country', 'content_rating']
n_items = len(df)

# Amelyik kategórinál az összes elem kevesebb mint 2% tartozik ott OTHER kategóriába raktuk őket

In [16]:
for feat in categorical_features:
    
    print("A %s feldolgozása. Egyedi mezők száma: %d." % (feat, df[feat].nunique()))
    
    if df[feat].nunique() < 50:

        print(df[feat].unique())
        print(df.groupby(feat).count().iloc[:,0])
        
        # Itt rakjuk át a OTHER kategóriába a cuccokat
        for feat_value in df[feat]:
            if (len(df[df[feat] == feat_value]) / n_items < 0.02):
                print("A %s kategória hozzáadása az OTHER kategoriához" % feat_value)
                df[feat] = df[feat].apply(lambda x: "OTHER" if x == feat_value else x, 1)

A color feldolgozása. Egyedi mezők száma: 2.
['Color' ' Black and White']
color
 Black and White     124
Color               3632
Name: director_name, dtype: int64
A director_name feldolgozása. Egyedi mezők száma: 1659.
A actor_1_name feldolgozása. Egyedi mezők száma: 1428.
A actor_2_name feldolgozása. Egyedi mezők száma: 2188.
A actor_3_name feldolgozása. Egyedi mezők száma: 2587.
A language feldolgozása. Egyedi mezők száma: 34.
['English' 'Mandarin' 'Aboriginal' 'Spanish' 'French' 'Filipino' 'Maya'
 'Kazakh' 'Cantonese' 'Japanese' 'Aramaic' 'Italian' 'Dutch' 'Dari'
 'German' 'Mongolian' 'Thai' 'Bosnian' 'Korean' 'Hungarian' 'Hindi'
 'Danish' 'Portuguese' 'Norwegian' 'Czech' 'Russian' 'None' 'Zulu'
 'Hebrew' 'Arabic' 'Vietnamese' 'Indonesian' 'Romanian' 'Persian']
language
Aboriginal       2
Arabic           1
Aramaic          1
Bosnian          1
Cantonese        7
Czech            1
Danish           3
Dari             2
Dutch            3
English       3598
Filipino         1
French

A French kategória hozzáadása az OTHER kategoriához
A Spanish kategória hozzáadása az OTHER kategoriához
A German kategória hozzáadása az OTHER kategoriához
A Hindi kategória hozzáadása az OTHER kategoriához
A Arabic kategória hozzáadása az OTHER kategoriához
A French kategória hozzáadása az OTHER kategoriához
A Spanish kategória hozzáadása az OTHER kategoriához
A Spanish kategória hozzáadása az OTHER kategoriához
A Danish kategória hozzáadása az OTHER kategoriához
A Vietnamese kategória hozzáadása az OTHER kategoriához
A Hindi kategória hozzáadása az OTHER kategoriához
A Italian kategória hozzáadása az OTHER kategoriához
A Portuguese kategória hozzáadása az OTHER kategoriához
A Indonesian kategória hozzáadása az OTHER kategoriához
A Japanese kategória hozzáadása az OTHER kategoriához
A Indonesian kategória hozzáadása az OTHER kategoriához
A Romanian kategória hozzáadása az OTHER kategoriához
A Persian kategória hozzáadása az OTHER kategoriához
A Norwegian kategória hozzáadása az OTHER

A Belgium kategória hozzáadása az OTHER kategoriához
A Japan kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Russia kategória hozzáadása az OTHER kategoriához
A Greece kategória hozzáadása az OTHER kategoriához
A Australia kategória hozzáadása az OTHER kategoriához
A Spain kategória hozzáadása az OTHER kategoriához
A China kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Ireland kategória hozzáadása az OTHER kategoriához
A Spain kategória hozzáadása az OTHER kategoriához
A Spain kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Taiwan kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Official site kategória hozzáadása az OTHER kategoriához
A Australia kategória hozzáadása az OTHER kategoriához
A 

A Iran kategória hozzáadása az OTHER kategoriához
A Norway kategória hozzáadása az OTHER kategoriához
A New Zealand kategória hozzáadása az OTHER kategoriához
A Australia kategória hozzáadása az OTHER kategoriához
A Afghanistan kategória hozzáadása az OTHER kategoriához
A Japan kategória hozzáadása az OTHER kategoriához
A Italy kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Italy kategória hozzáadása az OTHER kategoriához
A Iran kategória hozzáadása az OTHER kategoriához
A Ireland kategória hozzáadása az OTHER kategoriához
A Canada kategória hozzáadása az OTHER kategoriához
A Iran kategória hozzáadása az OTHER kategoriához
A content_rating feldolgozása. Egyedi mezők száma: 12.
['PG-13' 'PG' 'G' 'R' 'Approved' 'NC-17' 'X' 'Not Rated' 'Unrated' 'M'
 'GP' 'Passed']
content_rating
Approved       17
G              87
GP              1
M               2
NC-17           6
Not Rated      34
PG            566
PG-13        1308
Passed          3


In [17]:
df = pd.get_dummies(df, columns=['color'])

# Numpy package használata

In [18]:
alma = [1, 2, 3]

In [19]:
korte = np.array([1, 2, 3]) # lista kell az array-be 

In [20]:
type(korte), type(alma) # más a válto typusa is

(numpy.ndarray, list)

In [21]:
alma = np.array([1,2,3], dtype = np.float32)

In [22]:
alma = np.empty((2, 3)) # lefoglalása a memóriának

In [23]:
alma # nem nullákkal van inicializálva

array([[2.9615e-319, 7.5142e-319, 8.7400e-321],
       [1.0716e-320, 0.0000e+000, 0.0000e+000]])

In [24]:
nullak = np.zeros((2,1))

In [25]:
nullak

array([[0.],
       [0.]])

In [26]:
egyesek = np.ones((1, 4))

In [27]:
egyesek[0,:]

array([1., 1., 1., 1.])

In [28]:
diagonal_matrix = np.eye(100)

In [29]:
diagonal_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [31]:
b, a

(array([0, 1, 2, 3]), array([20, 30, 40, 50]))

In [32]:
b-a

array([-20, -29, -38, -47])

In [33]:
b<2

array([ True,  True, False, False])

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [6, 7]])

In [35]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 2]
 [6 7]]


In [36]:
A*B # element wise operation

array([[ 1,  4],
       [18, 28]])

In [37]:
A.dot(B) # vectorial product

array([[13, 16],
       [27, 34]])

In [38]:
np.random.seed(33)

In [39]:
np.random.random((3,3))

array([[0.24851013, 0.44997542, 0.4109408 ],
       [0.26029969, 0.87039569, 0.18503993],
       [0.01966143, 0.95325203, 0.6804508 ]])

In [40]:
A.max()

4